"""empleados_m2m_tareas

Revision ID: 19eda2ed9af2
Revises: 2feded51871f
Create Date: 2026-05-01 21:34:59.154382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19eda2ed9af2'
down_revision = '2feded51871f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarea_excepcional_empleados',
    sa.Column('tarea_id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas_excepcionales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tarea_id', 'empleado_id')
    )
    op.create_table('tarea_programada_empleados',
    sa.Column('tarea_id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas_programadas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tarea_id', 'empleado_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarea_programada_empleados')
    op.drop_table('tarea_excepcional_empleados')
    # ### end Alembic commands ###
