"""empleados y empleado_id en tareas y plantillas

Revision ID: 2feded51871f
Revises: 5aa35caab574
Create Date: 2026-05-01 21:16:29.815498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2feded51871f'
down_revision = '5aa35caab574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barrio_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['barrio_id'], ['barrios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plantillas_tarea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empleado_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'empleados', ['empleado_id'], ['id'])

    with op.batch_alter_table('tareas_excepcionales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empleado_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'empleados', ['empleado_id'], ['id'])

    with op.batch_alter_table('tareas_programadas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empleado_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'empleados', ['empleado_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas_programadas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('empleado_id')

    with op.batch_alter_table('tareas_excepcionales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('empleado_id')

    with op.batch_alter_table('plantillas_tarea', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('empleado_id')

    op.drop_table('empleados')
    # ### end Alembic commands ###
