"""initial

Revision ID: 423107f54206
Revises: 
Create Date: 2026-03-12 13:50:41.380461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423107f54206'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barrios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('color_primario', sa.String(length=7), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plantillas_tarea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barrio_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('frecuencia', sa.Enum('diaria', 'semanal', name='frecuencia_tarea'), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=True),
    sa.Column('horario', sa.Time(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['barrio_id'], ['barrios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barrio_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('rol', sa.Enum('intendente', 'encargado', name='rol_usuario'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['barrio_id'], ['barrios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tareas_excepcionales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barrio_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('horario', sa.Time(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('asignado_a', sa.Integer(), nullable=True),
    sa.Column('creada_por', sa.Integer(), nullable=False),
    sa.Column('prioridad', sa.Enum('baja', 'media', 'alta', name='prioridad_tarea'), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'completada', name='estado_excepcional'), nullable=False),
    sa.Column('completada_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asignado_a'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['barrio_id'], ['barrios.id'], ),
    sa.ForeignKeyConstraint(['creada_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tareas_programadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plantilla_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('horario', sa.Time(), nullable=False),
    sa.Column('asignado_a', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'completada', 'no_realizada', name='estado_programada'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('completada_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asignado_a'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['plantilla_id'], ['plantillas_tarea.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('justificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarea_programada_id', sa.Integer(), nullable=True),
    sa.Column('tarea_excepcional_id', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tarea_excepcional_id'], ['tareas_excepcionales.id'], ),
    sa.ForeignKeyConstraint(['tarea_programada_id'], ['tareas_programadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('justificaciones')
    op.drop_table('tareas_programadas')
    op.drop_table('tareas_excepcionales')
    op.drop_table('usuarios')
    op.drop_table('plantillas_tarea')
    op.drop_table('barrios')
    # ### end Alembic commands ###
